/* File generated by summboundverify */

#include <fcntl.h>
#include <unistd.h>
#include <stdio.h>
#include <sys/types.h>

#define ARRAY_SIZE_1 4
#define FNAME_SIZE_1 5

ssize_t concrete_write_and_seek(int fd, const char *data)
{
  ssize_t written = write(fd, data, 4);
  if (written < 0)
    return -1;
  off_t pos = lseek(fd, 0, 0);
  if (pos < 0)
    return -1;
  return written;
}

void test_1()
{
  char data[ARRAY_SIZE_1];
  for (int data_idx_1 = 0; data_idx_1 < ARRAY_SIZE_1; data_idx_1++)
  {
    data[data_idx_1] = __sym_var_array("data", data_idx_1, sizeof(char) * 8);
  }

  data[ARRAY_SIZE_1 - 1] = '\0';
  char __fname_fd[FNAME_SIZE_1];
  for (int __fname_fd_idx_1 = 0; __fname_fd_idx_1 < FNAME_SIZE_1; __fname_fd_idx_1++)
  {
    __fname_fd[__fname_fd_idx_1] = __sym_var_array("__fname_fd", __fname_fd_idx_1, sizeof(char) * 8);
  }

  __fname_fd[FNAME_SIZE_1 - 1] = '\0';
  __assume((__fname_fd[0] != '.') | (__fname_fd[1] != 0));
  __assume(((__fname_fd[0] != '.') | (__fname_fd[1] != '.')) | (__fname_fd[2] != 0));
  for (int __i___fname_fd = 0; __i___fname_fd < FNAME_SIZE_1; __i___fname_fd++)
  {
    __assume(__fname_fd[__i___fname_fd] != '/');
  }

  __file_create(__fname_fd);
  int fd = __file_open(__fname_fd, "w");
  __mem_addr("data", data, ARRAY_SIZE_1);
  ssize_t ret = concrete_write_and_seek(fd, data);
  sbv_record("test_1", &ret, sizeof(ssize_t) * 8, 0);
  return ;
}

int main()
{
  test_1();
  return 0;
}