/* File generated by summboundverify */

#include <fcntl.h>
#include <unistd.h>
#include <stdio.h>
#include <sys/types.h>

#define POINTER_SIZE 5
#define FUEL 5
#define ARRAY_SIZE_1 5

int concrete_append_to_file(const char *path)
{
  int fd = open(path, (O_WRONLY | O_CREAT) | O_APPEND, 0644);
  if (fd < 0)
    return -1;
  write(fd, "ab", 2);
  lseek(fd, 0, 0);
  write(fd, "cd", 2);
  return fd;
}

void test_1()
{
  char path[ARRAY_SIZE_1];
  for (int path_idx_1 = 0; path_idx_1 < ARRAY_SIZE_1; path_idx_1++)
  {
    path[path_idx_1] = __sym_var_array("path", path_idx_1, sizeof(char) * 8);
  }

  path[ARRAY_SIZE_1 - 1] = '\0';
  __assume(path[0] != 0);
  __assume((path[0] != '.') | (path[1] != 0));
  __assume(((path[0] != '.') | (path[1] != '.')) | (path[2] != 0));
  for (int __i_path = 0; __i_path < 5; __i_path++)
    __assume(path[__i_path] != '/');

  __file_addr("path", path);
  int ret = concrete_append_to_file(path);
  sbv_record("test_1", &ret, sizeof(int) * 8, 0);
  return ;
}

int main()
{
  test_1();
  return 0;
}