/* File generated by summboundverify */

#include <fcntl.h>
#include <unistd.h>
#include <stdio.h>
#include <sys/types.h>

#define POINTER_SIZE 5
#define FUEL 5
#define ARRAY_SIZE_1 5
#define MAX_NUM_1 5

int concrete_save_data(const char *path, const char *data, size_t len)
{
  int fd = open(path, (O_WRONLY | O_CREAT) | O_TRUNC, 0644);
  if (fd < 0)
    return -1;
  size_t total = 0;
  while (total < len)
  {
    ssize_t n = write(fd, data + total, len - total);
    if (n <= 0)
    {
      close(fd);
      return -1;
    }
    total += n;
  }

  close(fd);
  return 0;
}

void test_1()
{
  char path[ARRAY_SIZE_1];
  for (int path_idx_1 = 0; path_idx_1 < ARRAY_SIZE_1; path_idx_1++)
  {
    path[path_idx_1] = __sym_var_array("path", path_idx_1, sizeof(char) * 8);
  }

  path[ARRAY_SIZE_1 - 1] = '\0';
  char data[ARRAY_SIZE_1];
  for (int data_idx_1 = 0; data_idx_1 < ARRAY_SIZE_1; data_idx_1++)
  {
    data[data_idx_1] = __sym_var_array("data", data_idx_1, sizeof(char) * 8);
  }

  data[ARRAY_SIZE_1 - 1] = '\0';
  size_t len = __sym_var_named("len", sizeof(size_t) * 8);
  size_t max_2 = MAX_NUM_1;
  __assume(_ULE_(len, max_2));
  __assume(path[0] != 0);
  __assume((path[0] != '.') | (path[1] != 0));
  __assume(((path[0] != '.') | (path[1] != '.')) | (path[2] != 0));
  for (int __i_path = 0; __i_path < 5; __i_path++)
    __assume(path[__i_path] != '/');

  __file_addr("path", path);
  int ret = concrete_save_data(path, data, len);
  sbv_record("test_1", &ret, sizeof(int) * 8, 0);
  return ;
}

int main()
{
  test_1();
  return 0;
}