/* File generated by summboundverify */

#define NULL ((void*)0)
#define INT_SIZE (sizeof(int) * 8)
#define LONG_SIZE (sizeof(long) * 8)
#define CHAR_SIZE (sizeof(char) * 8)
#define PTR_SIZE (sizeof(void*) * 8)
typedef void* symbolic;
typedef int state_t;
typedef unsigned int size_t;
typedef unsigned int cnstr_t;
typedef unsigned int result_t;
typedef unsigned int list_t;

cnstr_t _ULE_(symbolic var1, symbolic var2) {return 0;}
cnstr_t get_cnstr(symbolic var, size_t size) {return 0;}
int is_sat(cnstr_t cnstr) {return 0;}
result_t check_implications(char* constraint1, char* constraint2) {return 0;}
state_t save_current_state() {return 0;}
symbolic sym_var_array(char* name, size_t index, size_t size) {return 0;}
symbolic sym_var_named(char* name, size_t size) {return 0;}
void assume(cnstr_t cnstr) {return;}
void halt_all(state_t state) {return;}
void mem_addr(char* name, void* addr, size_t length) {return;}
void print_counterexamples(result_t result) {return;}
void store_cnstr(char* name, cnstr_t constraint) {return;}
void sym_var_bytes(char* name, void* dst, size_t size) {return;}

cnstr_t _AND_(cnstr_t cnstr1, cnstr_t cnstr2) {return 0;}
cnstr_t _EQ_(symbolic var1, symbolic var2) {return 0;}
cnstr_t _GE_(symbolic var1, symbolic var2) {return 0;}
cnstr_t _GT_(symbolic var1, symbolic var2) {return 0;}
cnstr_t _ITE_(cnstr_t cnstr1, cnstr_t cnstr2, cnstr_t cnstr3) {return 0;}
cnstr_t _ITE_VAR_(cnstr_t cnstr1, symbolic var1, symbolic var2) {return 0;}
cnstr_t _LE_(symbolic var1, symbolic var2) {return 0;}
cnstr_t _LT_(symbolic var1, symbolic var2) {return 0;}
cnstr_t _NEQ_(symbolic var1, symbolic var2) {return 0;}
cnstr_t _NOT_(cnstr_t cnstr) {return 0;}
cnstr_t _OR_(cnstr_t cnstr1, cnstr_t cnstr2) {return 0;}
cnstr_t _UGE_(symbolic var1, symbolic var2) {return 0;}
cnstr_t _UGT_(symbolic var1, symbolic var2) {return 0;}
cnstr_t _ULT_(symbolic var1, symbolic var2) {return 0;}
void _assert(int expr){return;}
void allocd(void* ptr, size_t size) {return;}
void cond_write(void* ptr, symbolic c, cnstr_t pc) {return;}
int is_certain(cnstr_t cnstr){return 0;}
int is_symbolic(symbolic sym_var) {return 0;} 
list_t lst_cons(symbolic value, list_t lst) {return 0;}
cnstr_t lst_empty(list_t lst) {return 0;}
symbolic lst_hd(list_t lst) {return 0;}
size_t lst_len(list_t lst) {return 0;}
list_t lst_mk(){return 0;}
list_t lst_nbytes(char c, size_t n) {return 0;}
list_t lst_tl(list_t lst) {return 0;}
list_t lst_zeros(size_t n) {return 0;}
long maximize(symbolic sym_var){return 0;}
void* mem_alloc(size_t bytes) {return 0;}
void  mem_free(void* ptr) {return ;}
long minimize(symbolic sym_var){return 0;}
size_t n_allocd(void* ptr) {return 0;}
void pop_pc(){return;}
void push_pc(){return;}
symbolic sym_var(size_t size) {return 0;}

#define POINTER_SIZE 5
#define FUEL 5
#define ARRAY_SIZE_1 3

int concrete_tolower(int c)
{
  if ((c >= 65) && (c <= 90))
  {
    return c + 32;
  }
  return c;
}

void test_1()
{
  int c = sym_var_named("c", sizeof(int) * 8);
  state_t initial_state = save_current_state();
  int ret1 = concrete_tolower(c);
  cnstr_t cnstr1 = get_cnstr(&ret1, sizeof(int) * 8);
  store_cnstr("cnctr_test1", cnstr1);
  halt_all(initial_state);
  int ret2 = tolower(c);
  cnstr_t cnstr2 = get_cnstr(&ret2, sizeof(int) * 8);
  store_cnstr("summ_test1", cnstr2);
  halt_all(NULL);
  result_t result = check_implications("cnctr_test1", "summ_test1");
  print_counterexamples(result);
  return ;
}

int main()
{
  test_1();
}