/* File generated by summboundverify */

#include <fcntl.h>
#include <unistd.h>
#include <stdio.h>
#include <sys/types.h>

#define ARRAY_SIZE_1_VAR1 4
#define ARRAY_SIZE_1_VAR2 4

void concrete_copy_buffer(char *dst, const char *src)
{
  for (int i = 0; i < 4; i++)
    dst[i] = src[i];

}

void test_1()
{
  char dst[ARRAY_SIZE_1_VAR1];
  for (int dst_idx_1 = 0; dst_idx_1 < ARRAY_SIZE_1_VAR1; dst_idx_1++)
  {
    dst[dst_idx_1] = __sym_var_array("dst", dst_idx_1, sizeof(char) * 8);
  }

  dst[ARRAY_SIZE_1_VAR1 - 1] = '\0';
  char src[ARRAY_SIZE_1_VAR2];
  for (int src_idx_1 = 0; src_idx_1 < ARRAY_SIZE_1_VAR2; src_idx_1++)
  {
    src[src_idx_1] = __sym_var_array("src", src_idx_1, sizeof(char) * 8);
  }

  src[ARRAY_SIZE_1_VAR2 - 1] = '\0';
  __mem_addr("dst", dst, ARRAY_SIZE_1_VAR1);
  __mem_addr("src", src, ARRAY_SIZE_1_VAR2);
  concrete_copy_buffer(dst, src);
  sbv_record("test_1", 0, 0, 0);
  return ;
}

int main()
{
  test_1();
  return 0;
}