/* File generated by summboundverify */

#include <fcntl.h>
#include <unistd.h>
#include <stdio.h>
#include <sys/types.h>

#define ARRAY_SIZE_1 4
#define FNAME_SIZE_1 5

ssize_t concrete_read_from_fd(int fd, char *buf)
{
  ssize_t nread = read(fd, buf, 4);
  if (nread < 0)
    return -1;
  return nread;
}

void test_1()
{
  char buf[ARRAY_SIZE_1];
  for (int buf_idx_1 = 0; buf_idx_1 < ARRAY_SIZE_1; buf_idx_1++)
  {
    buf[buf_idx_1] = __sym_var_array("buf", buf_idx_1, sizeof(char) * 8);
  }

  buf[ARRAY_SIZE_1 - 1] = '\0';
  char __fname_fd[FNAME_SIZE_1];
  for (int __fname_fd_idx_1 = 0; __fname_fd_idx_1 < FNAME_SIZE_1; __fname_fd_idx_1++)
  {
    __fname_fd[__fname_fd_idx_1] = __sym_var_array("__fname_fd", __fname_fd_idx_1, sizeof(char) * 8);
  }

  __fname_fd[FNAME_SIZE_1 - 1] = '\0';
  __assume((__fname_fd[0] != '.') | (__fname_fd[1] != 0));
  __assume(((__fname_fd[0] != '.') | (__fname_fd[1] != '.')) | (__fname_fd[2] != 0));
  for (int __i___fname_fd = 0; __i___fname_fd < 5; __i___fname_fd++)
  {
    __assume(__fname_fd[__i___fname_fd] != '/');
  }

  __file_create(__fname_fd);
  int fd = __file_open(__fname_fd, "w+");
  char __data_fd[5];
  for (int __data_fd_idx_1 = 0; __data_fd_idx_1 < 5; __data_fd_idx_1++)
  {
    __data_fd[__data_fd_idx_1] = __sym_var_array("__data_fd", __data_fd_idx_1, sizeof(char) * 8);
  }

  __data_fd[5 - 1] = '\0';
  __file_write(fd, __data_fd, 4);
  __file_set_offset(fd, 0);
  __mem_addr("buf", buf, ARRAY_SIZE_1);
  ssize_t ret = concrete_read_from_fd(fd, buf);
  sbv_record("test_1", &ret, sizeof(ssize_t) * 8, 0);
  return ;
}

int main()
{
  test_1();
  return 0;
}