/* File generated by summboundverify */

#include <fcntl.h>
#include <unistd.h>
#include <stdio.h>
#include <sys/types.h>

#define ARRAY_SIZE_1 5
#define MAX_NUM_1 5
#define FNAME_SIZE_1 3

void test_1()
{
  char buf[ARRAY_SIZE_1];
  for (int buf_idx_1 = 0; buf_idx_1 < ARRAY_SIZE_1; buf_idx_1++)
  {
    buf[buf_idx_1] = __sym_var_array("buf", buf_idx_1, sizeof(char) * 8);
  }

  buf[ARRAY_SIZE_1 - 1] = '\0';
  size_t count = __sym_var_named("count", sizeof(size_t) * 8);
  size_t max_2 = MAX_NUM_1;
  __assume(_ULE_(count, max_2));
  char __fname_fd[FNAME_SIZE_1];
  for (int __fname_fd_idx_1 = 0; __fname_fd_idx_1 < FNAME_SIZE_1; __fname_fd_idx_1++)
  {
    __fname_fd[__fname_fd_idx_1] = __sym_var_array("__fname_fd", __fname_fd_idx_1, sizeof(char) * 8);
  }

  __fname_fd[FNAME_SIZE_1 - 1] = '\0';
  __assume((__fname_fd[0] != '.') | (__fname_fd[1] != 0));
  __assume(((__fname_fd[0] != '.') | (__fname_fd[1] != '.')) | (__fname_fd[2] != 0));
  for (int __i___fname_fd = 0; __i___fname_fd < FNAME_SIZE_1; __i___fname_fd++)
  {
    __assume(__fname_fd[__i___fname_fd] != '/');
  }

  __file_create(__fname_fd);
  int fd = __file_open(__fname_fd, "w+");
  char __data_fd[4];
  for (int __data_fd_idx_1 = 0; __data_fd_idx_1 < 4; __data_fd_idx_1++)
  {
    __data_fd[__data_fd_idx_1] = __sym_var_array("__data_fd", __data_fd_idx_1, sizeof(char) * 8);
  }

  __data_fd[4 - 1] = '\0';
  __file_write(fd, __data_fd, 3);
  __file_set_offset(fd, 0);
  __mem_addr("buf", buf, ARRAY_SIZE_1);
  ssize_t ret = write(fd, buf, count);
  sbv_record("test_1", &ret, sizeof(ssize_t) * 8, 0);
  return ;
}

int main()
{
  test_1();
  return 0;
}