/* File generated by summboundverify */

#define NULL ((void*)0)
#define INT_SIZE (sizeof(int) * 8)
#define LONG_SIZE (sizeof(long) * 8)
#define CHAR_SIZE (sizeof(char) * 8)
#define PTR_SIZE (sizeof(void*) * 8)

typedef void *symbolic;
typedef int state_t;
typedef unsigned int cnstr_t;
typedef unsigned int result_t;
typedef unsigned int list_t;

typedef unsigned int size_t;
typedef int ssize_t;
typedef int mode_t;
typedef void *FILE;

FILE *__FILE_from_fd(int fd) { return 0; }
cnstr_t _NEQ_(symbolic var1, symbolic var2) { return 0; }
cnstr_t _OR_(cnstr_t cnstr1, cnstr_t cnstr2) { return 0; }
cnstr_t _ULE_(symbolic var1, symbolic var2) { return 0; }
cnstr_t __get_cnstr(symbolic var, size_t size) { return 0; }
int __file_create(const char *name) { return 0; }
int __file_open(const char *name, const char *flags) { return 0; }
int __is_symbolic(symbolic var) { return 0; }
long __maximize(symbolic var) { return 0; }
result_t __check_implications(char *summ, char *cncrt) { return 0; }
ssize_t __file_set_offset(int fd, size_t offset) { return 0; }
ssize_t __file_write(int fd, const void *buffer, size_t count) { return 0; }
state_t __save_current_state(void) { return 0; }
symbolic __sym_var_array(char *name, size_t index, size_t size) { return 0; }
symbolic __sym_var_named(char *name, size_t size) { return 0; }
void __assume(cnstr_t cnstr) { }
void __file_addr(char *name, const char *path) { }
void __halt_all(state_t state) { }
void __mem_addr(char *name, void *addr, size_t n) { }
void __print_counterexamples(result_t result) { }
void __store_cnstr(char *name, cnstr_t constraint) { }

#define ARRAY_SIZE_1 5
#define MAX_NUM_1 5
#define FNAME_SIZE_1 3

ssize_t summ_write(int fd, const void *buf, size_t count)
{
  if (!__is_symbolic(count))
    return __file_write(fd, buf, count);
  size_t max = __maximize(count);
  for (size_t n = 0; n < max; n++)
  {
    if (count == n)
      return __file_write(fd, buf, n);
  }

  return __file_write(fd, buf, max);
}

void test_1()
{
  char buf[ARRAY_SIZE_1];
  for (int buf_idx_1 = 0; buf_idx_1 < ARRAY_SIZE_1; buf_idx_1++)
  {
    buf[buf_idx_1] = __sym_var_array("buf", buf_idx_1, sizeof(char) * 8);
  }

  buf[ARRAY_SIZE_1 - 1] = '\0';
  size_t count = __sym_var_named("count", sizeof(size_t) * 8);
  size_t max_1 = MAX_NUM_1;
  __assume(_ULE_(count, max_1));
  char __fname_fd[FNAME_SIZE_1];
  for (int __fname_fd_idx_1 = 0; __fname_fd_idx_1 < FNAME_SIZE_1; __fname_fd_idx_1++)
  {
    __fname_fd[__fname_fd_idx_1] = __sym_var_array("__fname_fd", __fname_fd_idx_1, sizeof(char) * 8);
  }

  __fname_fd[FNAME_SIZE_1 - 1] = '\0';
  __assume(_OR_(_NEQ_(__fname_fd[0], '.'), _NEQ_(__fname_fd[1], 0)));
  __assume(_OR_(_OR_(_NEQ_(__fname_fd[0], '.'), _NEQ_(__fname_fd[1], '.')), _NEQ_(__fname_fd[2], 0)));
  for (int __i___fname_fd = 0; __i___fname_fd < FNAME_SIZE_1; __i___fname_fd++)
  {
    __assume(_NEQ_(__fname_fd[__i___fname_fd], '/'));
  }

  __file_create(__fname_fd);
  int fd = __file_open(__fname_fd, "w+");
  char __data_fd[4];
  for (int __data_fd_idx_1 = 0; __data_fd_idx_1 < 4; __data_fd_idx_1++)
  {
    __data_fd[__data_fd_idx_1] = __sym_var_array("__data_fd", __data_fd_idx_1, sizeof(char) * 8);
  }

  __data_fd[4 - 1] = '\0';
  __file_write(fd, __data_fd, 3);
  __file_set_offset(fd, 0);
  __mem_addr("buf", buf, ARRAY_SIZE_1);
  ssize_t ret = summ_write(fd, buf, count);
  cnstr_t cnstr = __get_cnstr(&ret, sizeof(ssize_t) * 8);
  __store_cnstr("summ_test1", cnstr);
  __halt_all(NULL);
  return ;
}

int main()
{
  test_1();
  return 0;
}