import os

from pathlib import Path
from summboundverify.utils.files import tmp_file


class Generator:
    def __init__(
        self,
        outputfile: str | Path,
        concretefile: str | Path | None,
        summaryfile: str | Path | None
    ):
        self.concretefile = Path(concretefile) if concretefile else None
        self.summaryfile = Path(summaryfile) if summaryfile else None

        self.outputfile = Path(outputfile)

        self.tmp_concrete = self.add_fake_include(self.concretefile)
        self.tmp_summary = self.add_fake_include(self.summaryfile)

        self.watermark = "/* File generated by summboundverify */"

    def add_fake_include(self, file: Path | None):
        if not file:
            return None

        fake_include = '#include <stdlib.h>\n'
        content = file.read_text()
        content = fake_include + content
        suffix = f"__{file.name}"
        tmp = tmp_file(suffix)
        tmp.write_text(content)
        return tmp

    def write_to_file(self, code: str, header: str | list[str]):
        if isinstance(header, list):
            header = '\n'.join(header)

        content = (
            self.watermark + "\n\n" +
            header + "\n\n" +
            code
        )
        self.outputfile.write_text(content)

    def remove_files(self, *files):
        for f in files:
            if f and os.path.exists(f):
                os.remove(f)
