from abc import ABC, abstractmethod
from pathlib import Path

from pycparser import c_generator
from pycparser.c_ast import (
    ID,
    Return,
    FuncDef,
    FileAST,
    FuncCall,
    Compound,
    Constant,
)

from summboundverify.api import (
    macros,
    type_stubs,
    required_stubs,
    sra_stubs,
)
from summboundverify.utils.visitors import FuncCallsVisitor

from .test import TestGen
from .api import halt_all, save_current_state
from .parser import FunctionParser, ParsedFunctions
from .test.args.visitors.structs import StructVisitor

from .utils import *


class ValidationGenerator(ABC):
    """Common functionality for generating validation test harnesses."""

    def __init__(
        self,
        concrete_file: str | Path | None,
        summary_file: str | Path | None,
        outputfile: str | Path,
        *,
        arraysize=[5],
        nullbytes=[],
        maxnum=[],
        maxnames=[],
        default={},
        concrete_arrays={},
        pointersize=5,
        fuel=5,
        no_api=False,
        cncrt_name: str | None = None,
        summ_name: str | None = None,
        argspec: dict | None = None,
    ):
        self.watermark = "/* File generated by summboundverify */"

        self.concretefile = Path(concrete_file) if concrete_file else None
        self.summaryfile = Path(summary_file) if summary_file else None
        self.outputfile = Path(outputfile)

        self.arraysize = arraysize
        self.nullbytes = nullbytes
        self.maxnum = maxnum
        self.maxnames = maxnames
        self.default = default
        self.concrete_arrays = concrete_arrays
        self.pointersize = pointersize
        self.fuel = fuel
        self.no_api = no_api

        self.summ_name = summ_name
        self.cncrt_name = cncrt_name
        self.argspec = argspec or {}

    def _save_file(self, code: str, header: str | list[str]):
        if isinstance(header, list):
            header = "\n".join(header)

        content = (
            self.watermark
            + "\n\n"
            + header
            + "\n\n"
            + code
        )

        self.outputfile.write_text(content)

    def get_api_calls(self, funcs):
        api_calls = set()
        complete_api = sra_stubs()
        required_api = required_stubs()

        for i, func in enumerate(funcs, 1):
            visitor = FuncCallsVisitor()
            visitor.visit(func)
            called = visitor.fcalls()

            if i == len(funcs) and not called:
                called = complete_api

            api_calls.update(
                c
                for c in called
                if c in complete_api and c not in required_api
            )

        validation_defs = list(required_api.values())
        api_defs = [complete_api[call] for call in api_calls]

        return sorted(validation_defs + api_defs)

    def get_array_size(self, id):
        if isinstance(self.arraysize[id - 1], list):
            array_size = []

            for x, _ in enumerate(self.arraysize[id - 1]):
                name = f"{ARRAY_SIZE_MACRO}_{id}_VAR{x + 1}"
                array_size.append(name)

        else:
            arr_id = min(id, len(self.arraysize))
            array_size = f"{ARRAY_SIZE_MACRO}_{arr_id}"

        return array_size

    def get_null_byte(self, id):
        if self.nullbytes:
            if id <= len(self.nullbytes):
                position = self.nullbytes[id - 1]
            else:
                position = self.nullbytes[-1]

            if isinstance(position, list):
                null_byte = []
                for x in position:
                    null_byte.append(x)
            else:
                null_byte = position

            return null_byte

        return self.nullbytes

    def get_dict_value(self, id, dict):
        if dict:
            if id <= len(dict):
                return dict[id - 1]
            return dict[-1]

        return dict

    def gen_headers(self, defs):
        headers = [
            macros(),
            *type_stubs(),
            "",
        ]

        if not self.no_api:
            headers += self.get_api_calls(defs)
            headers.append("")

        headers += [
            define_macro(POINTER_SIZE_MACRO, self.pointersize),
            define_macro(FUEL_MACRO, self.fuel),
        ]

        headers += self.gen_macros(ARRAY_SIZE_MACRO, self.arraysize)
        headers += self.gen_macros(MAX_MACRO, self.maxnum)

        return headers

    def gen_macros(self, macro, values=[]):
        macros = []

        for i, value in enumerate(values):
            if isinstance(value, list):
                stringlst = []

                for x, y in enumerate(value):
                    name = f"{macro}_{i + 1}_VAR{x + 1}"
                    stringlst.append(define_macro(name, y))

                string = "\n".join(stringlst)

            else:
                name = f"{macro}_{i + 1}"
                string = define_macro(name, value)

            macros.append(string)

        return macros

    def gen_test(self, testname, args, ret_type, cncrt_name, summ_name, id):
        array_size = self.get_array_size(id)
        null_bytes = self.get_null_byte(id)
        default = self.get_dict_value(id, self.default)
        concrete = self.get_dict_value(id, self.concrete_arrays)

        max_value = f"{MAX_MACRO}_{id}" if id <= len(self.maxnum) else None

        test_gen = self.test_generator(args, ret_type, cncrt_name, summ_name)

        return test_gen.create_test(
            testname,
            array_size,
            null_bytes,
            max_value,
            default,
            concrete,
            id,
        )

    def gen_tests(self, args, ret_type, cncrt_name, summ_name):
        test_defs = []
        main_body = []

        ntests = max(len(self.maxnum), len(self.arraysize))

        # Save fresh states between symbolic tests
        if self.symbolic:
            main_body += [
                save_current_state(f"fresh_state{i}")
                for i in range(1, ntests)
            ]

        for i in range(1, ntests + 1):
            test_name = f"test_{i}"

            test_code = self.gen_test(
                test_name, args,
                ret_type,
                cncrt_name,
                summ_name,
                i
            )

            test_defs.append(test_code)

            main_body.append(
                FuncCall(ID(test_name), None)
            )

            # Load a fresh symbolic state
            if self.symbolic and i < ntests:
                main_body.append(
                    halt_all(f"fresh_state{i}")
                )

        return test_defs, main_body

    def gen(self):
        fparser = FunctionParser(self.concretefile, self.summaryfile)
        parsed = fparser.parse(self.cncrt_name, self.summ_name)

        cncrt_name = parsed.concrete_name
        summ_name = parsed.summary_name

        functions = self.functions(parsed)

        function_defs = [
            f.definition if f else None
            for f in functions
        ]

        args = parsed.arguments
        ret_type = parsed.return_type

        header = self.gen_headers([
            f.definition if f else None
            for f in parsed.functions
        ])

        if None in function_defs:
            function_defs.remove(None)

        main = create_function(
            name="main",
            args=None,
            returnType="int",
        )

        structs = StructVisitor(self.concretefile).symbolic_structs()
        structs += StructVisitor(self.summaryfile).symbolic_structs()

        test_defs, main_body = self.gen_tests(
            args,
            ret_type,
            cncrt_name,
            summ_name
        )

        main_body.append(
            Return(Constant("int", "0"))
        )

        block = Compound(main_body)
        main_ast = FuncDef(main, None, block, None)

        gen_ast = FileAST(
            structs + function_defs + test_defs
        )

        gen_ast.ext.append(main_ast)

        generator = c_generator.CGenerator()
        generated_string = generator.visit(gen_ast)

        self._save_file(generated_string.rstrip(), header)

        return self.outputfile

    @property
    @abstractmethod
    def symbolic(self) -> bool:
        raise NotImplementedError

    @abstractmethod
    def functions(self, parsed: ParsedFunctions) -> list:
        raise NotImplementedError

    @abstractmethod
    def test_generator(self, args, ret_type, cname, sname) -> TestGen:
        raise NotImplementedError
