/* File generated by summboundverify */

#include <fcntl.h>
#include <unistd.h>
#include <stdio.h>
#include <sys/types.h>

#define POINTER_SIZE 5
#define FUEL 5
#define ARRAY_SIZE_1 4

int concrete_dup_write(int fd, const char *data)
{
  int fd2 = dup(fd);
  if (fd2 < 0)
    return -1;
  if (write(fd2, data, 4) != 4)
  {
    close(fd2);
    return -1;
  }
  close(fd2);
  return fd2;
}

void test_1()
{
  char data[ARRAY_SIZE_1];
  for (int data_idx_1 = 0; data_idx_1 < ARRAY_SIZE_1; data_idx_1++)
  {
    data[data_idx_1] = __sym_var_array("data", data_idx_1, sizeof(char) * 8);
  }

  data[ARRAY_SIZE_1 - 1] = '\0';
  char __fname_fd[5];
  for (int __fname_fd_idx_1 = 0; __fname_fd_idx_1 < 5; __fname_fd_idx_1++)
  {
    __fname_fd[__fname_fd_idx_1] = __sym_var_array("__fname_fd", __fname_fd_idx_1, sizeof(char) * 8);
  }

  __fname_fd[5 - 1] = '\0';
  __assume(__fname_fd[0] != 0);
  __assume((__fname_fd[0] != '.') | (__fname_fd[1] != 0));
  __assume(((__fname_fd[0] != '.') | (__fname_fd[1] != '.')) | (__fname_fd[2] != 0));
  for (int __i___fname_fd = 0; __i___fname_fd < 5; __i___fname_fd++)
    __assume(__fname_fd[__i___fname_fd] != '/');

  __file_create(__fname_fd);
  int fd = __file_open(__fname_fd, "w");
  int ret = concrete_dup_write(fd, data);
  sbv_record("test_1", &ret, sizeof(int) * 8, 0);
  return ;
}

int main()
{
  test_1();
  return 0;
}