/* File generated by summboundverify */

#define NULL ((void*)0)
#define INT_SIZE (sizeof(int) * 8)
#define LONG_SIZE (sizeof(long) * 8)
#define CHAR_SIZE (sizeof(char) * 8)
#define PTR_SIZE (sizeof(void*) * 8)

typedef void *symbolic;
typedef int state_t;
typedef unsigned int cnstr_t;
typedef unsigned int result_t;
typedef unsigned int list_t;

typedef unsigned int size_t;
typedef int ssize_t;
typedef int mode_t;
typedef void *FILE;

FILE *__FILE_from_fd(int fd) { return 0; }
cnstr_t _NEQ_(symbolic var1, symbolic var2) { return 0; }
cnstr_t _OR_(cnstr_t cnstr1, cnstr_t cnstr2) { return 0; }
cnstr_t _ULE_(symbolic var1, symbolic var2) { return 0; }
cnstr_t __get_cnstr(symbolic var, size_t size) { return 0; }
int __fd_from_FILE(FILE *fp) { return 0; }
int __file_create(const char *name) { return 0; }
int __file_open(const char *name, const char *flags) { return 0; }
result_t __check_implications(char *summ, char *cncrt) { return 0; }
ssize_t __file_set_offset(int fd, size_t offset) { return 0; }
ssize_t __file_write(int fd, const void *buffer, size_t count) { return 0; }
state_t __save_current_state(void) { return 0; }
symbolic __sym_var_array(char *name, size_t index, size_t size) { return 0; }
symbolic __sym_var_named(char *name, size_t size) { return 0; }
void __assume(cnstr_t cnstr) { }
void __file_addr(char *name, const char *path) { }
void __halt_all(state_t state) { }
void __mem_addr(char *name, void *addr, size_t n) { }
void __print_counterexamples(result_t result) { }
void __store_cnstr(char *name, cnstr_t constraint) { }

#define ARRAY_SIZE_1 4
#define FNAME_SIZE_1 5

size_t fwrite_to_fp(FILE *fp, const char *data)
{
  int fd = __fd_from_FILE(fp);
  if (fd < 0)
  {
    return 0;
  }
  ssize_t written = __file_write(fd, data, 4);
  if (written < 0)
  {
    return 0;
  }
  return written;
}

void test_1()
{
  char data[ARRAY_SIZE_1];
  for (int data_idx_1 = 0; data_idx_1 < ARRAY_SIZE_1; data_idx_1++)
  {
    data[data_idx_1] = __sym_var_array("data", data_idx_1, sizeof(char) * 8);
  }

  data[ARRAY_SIZE_1 - 1] = '\0';
  char __fname_fp[FNAME_SIZE_1];
  for (int __fname_fp_idx_1 = 0; __fname_fp_idx_1 < FNAME_SIZE_1; __fname_fp_idx_1++)
  {
    __fname_fp[__fname_fp_idx_1] = __sym_var_array("__fname_fp", __fname_fp_idx_1, sizeof(char) * 8);
  }

  __fname_fp[FNAME_SIZE_1 - 1] = '\0';
  __assume(_OR_(_NEQ_(__fname_fp[0], '.'), _NEQ_(__fname_fp[1], 0)));
  __assume(_OR_(_OR_(_NEQ_(__fname_fp[0], '.'), _NEQ_(__fname_fp[1], '.')), _NEQ_(__fname_fp[2], 0)));
  for (int __i___fname_fp = 0; __i___fname_fp < FNAME_SIZE_1; __i___fname_fp++)
  {
    __assume(_NEQ_(__fname_fp[__i___fname_fp], '/'));
  }

  __file_create(__fname_fp);
  int __fd_fp = __file_open(__fname_fp, "w");
  FILE *fp = __FILE_from_fd(__fd_fp);
  __mem_addr("data", data, ARRAY_SIZE_1);
  size_t ret = fwrite_to_fp(fp, data);
  cnstr_t cnstr = __get_cnstr(&ret, sizeof(size_t) * 8);
  __store_cnstr("summ_test1", cnstr);
  __halt_all(NULL);
  return ;
}

int main()
{
  test_1();
  return 0;
}