/* File generated by summboundverify */

#include <fcntl.h>
#include <unistd.h>
#include <stdio.h>
#include <sys/types.h>

#define ARRAY_SIZE_1 4
#define FNAME_SIZE_1 5

size_t concrete_fwrite_to_fp(FILE *fp, const char *data)
{
  return fwrite(data, 1, 4, fp);
}

void test_1()
{
  char data[ARRAY_SIZE_1];
  for (int data_idx_1 = 0; data_idx_1 < ARRAY_SIZE_1; data_idx_1++)
  {
    data[data_idx_1] = __sym_var_array("data", data_idx_1, sizeof(char) * 8);
  }

  data[ARRAY_SIZE_1 - 1] = '\0';
  char __fname_fp[FNAME_SIZE_1];
  for (int __fname_fp_idx_1 = 0; __fname_fp_idx_1 < FNAME_SIZE_1; __fname_fp_idx_1++)
  {
    __fname_fp[__fname_fp_idx_1] = __sym_var_array("__fname_fp", __fname_fp_idx_1, sizeof(char) * 8);
  }

  __fname_fp[FNAME_SIZE_1 - 1] = '\0';
  __assume((__fname_fp[0] != '.') | (__fname_fp[1] != 0));
  __assume(((__fname_fp[0] != '.') | (__fname_fp[1] != '.')) | (__fname_fp[2] != 0));
  for (int __i___fname_fp = 0; __i___fname_fp < FNAME_SIZE_1; __i___fname_fp++)
  {
    __assume(__fname_fp[__i___fname_fp] != '/');
  }

  __file_create(__fname_fp);
  int __fd_fp = __file_open(__fname_fp, "w");
  FILE *fp = __FILE_from_fd(__fd_fp);
  __mem_addr("data", data, ARRAY_SIZE_1);
  size_t ret = concrete_fwrite_to_fp(fp, data);
  sbv_record("test_1", &ret, sizeof(size_t) * 8, 0);
  return ;
}

int main()
{
  test_1();
  return 0;
}