/* File generated by summboundverify */

#define NULL ((void*)0)
#define INT_SIZE (sizeof(int) * 8)
#define LONG_SIZE (sizeof(long) * 8)
#define CHAR_SIZE (sizeof(char) * 8)
#define PTR_SIZE (sizeof(void*) * 8)

typedef void *symbolic;
typedef int state_t;
typedef unsigned int cnstr_t;
typedef unsigned int result_t;
typedef unsigned int list_t;

typedef unsigned int size_t;
typedef int ssize_t;
typedef int mode_t;
typedef void *FILE;

FILE *__FILE_from_fd(int fd) { return 0; }
cnstr_t _NEQ_(symbolic var1, symbolic var2) { return 0; }
cnstr_t _OR_(cnstr_t cnstr1, cnstr_t cnstr2) { return 0; }
cnstr_t _ULE_(symbolic var1, symbolic var2) { return 0; }
cnstr_t __get_cnstr(symbolic var, size_t size) { return 0; }
int __file_create(const char *name) { return 0; }
int __file_open(const char *name, const char *flags) { return 0; }
result_t __check_implications(char *summ, char *cncrt) { return 0; }
ssize_t __file_set_offset(int fd, size_t offset) { return 0; }
ssize_t __file_write(int fd, const void *buffer, size_t count) { return 0; }
state_t __save_current_state(void) { return 0; }
symbolic __sym_var_array(char *name, size_t index, size_t size) { return 0; }
symbolic __sym_var_named(char *name, size_t size) { return 0; }
void __assume(cnstr_t cnstr) { }
void __file_addr(char *name, const char *path) { }
void __halt_all(state_t state) { }
void __mem_addr(char *name, void *addr, size_t n) { }
void __print_counterexamples(result_t result) { }
void __store_cnstr(char *name, cnstr_t constraint) { }

#define ARRAY_SIZE_1 5

int create_file(const char *path)
{
  int ret = __file_create(path);
  return ret;
}

void test_1()
{
  char path[ARRAY_SIZE_1];
  for (int path_idx_1 = 0; path_idx_1 < ARRAY_SIZE_1; path_idx_1++)
  {
    path[path_idx_1] = __sym_var_array("path", path_idx_1, sizeof(char) * 8);
  }

  path[ARRAY_SIZE_1 - 1] = '\0';
  __assume(_OR_(_NEQ_(path[0], '.'), _NEQ_(path[1], 0)));
  __assume(_OR_(_OR_(_NEQ_(path[0], '.'), _NEQ_(path[1], '.')), _NEQ_(path[2], 0)));
  for (int __i_path = 0; __i_path < 5; __i_path++)
  {
    __assume(_NEQ_(path[__i_path], '/'));
  }

  __file_addr("path", path);
  int ret = create_file(path);
  cnstr_t cnstr = __get_cnstr(&ret, sizeof(int) * 8);
  __store_cnstr("summ_test1", cnstr);
  __halt_all(NULL);
  return ;
}

int main()
{
  test_1();
  return 0;
}